# Generated by Django 4.1.2 on 2022-12-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orders_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_gateway',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cooking', 'Cooking'), ('Packed', 'Packed'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
